stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
# source: https://medium.com/kinandcartacreated/setup-a-flutter-ci-cd-with-gitlab-ci-part-3-8e67c91c6da7
build-ios:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - wget https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.19.3-stable.zip
    - unzip flutter_macos_arm64_3.19.3-stable.zip
    - export PATH=$HOME/flutter/bin:$PATH
    - flutter doctor -v
    - flutter pub get
    - flutter clean
  script:
    - echo "Compiling the code for iOS..."
    - flutter build ipa
    #  - cd ios
    #  - xcodebuild clean archive -workspace Runner.xcworkspace -scheme Runner -archivePath RunnerArchive
    #  - xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build
  #artifacts:
    #paths:
    #  - ios/build/Runner.ipa
  after_script:
    - mv build/ios/ipa/AELF.ipa aelf-$CI_COMMIT_SHORT_SHA.ipa
  artifacts:
    name: aelf-$CI_COMMIT_SHORT_SHA.ipa
    paths:
      - aelf-$CI_COMMIT_SHORT_SHA.ipa
  tags:
    - saas-macos-medium-m1

build-android:
  image: ghcr.io/cirruslabs/flutter:3.19.3
  stage: build
  before_script:
    - flutter doctor -v
    - flutter pub get
    - flutter clean
  script:
    - echo "Compiling the code for Android..."
    - flutter build apk
  after_script:
    - mv build/app/outputs/apk/release/app-release.apk aelf-flutter-"$CI_COMMIT_SHORT_SHA".apk
  artifacts:
    name: aelf-flutter-$CI_COMMIT_SHORT_SHA
    paths:
      - aelf-flutter-$CI_COMMIT_SHORT_SHA.apk
  tags:
    - saas-linux-small-amd64

deploy-ios:
  stage: deploy
  #  dependencies:
  #  - build-ios
  needs: ["build-ios"]
  script:
    - echo "Uploading to testflight..."
    - xcrun altool --upload-app --type ios -f *.ipa --username $ci_username_apple --password $ci_pwd_apple
  tags:
    - macos
    - aelf
  rules:
    - if: $CI_COMMIT_TAG != null
