name: aelf_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.8
  flutter_html: 3.0.0-alpha.1
  flutter_linkify: ^5.0.2
  http: ^1.0.0
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.1.0
  sqlite3_flutter_libs: ^0.5.10
  shared_preferences: ^2.0.11
  connectivity_plus: ^2.3.9
  url_launcher: ^6.1.5
  package_info: ^2.0.2
  provider: ^6.0.1
  unorm_dart: ^0.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  wakelock: ^0.6.1+2
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_icons:
  image_path: "assets/icons/aelf_logo_1024.png"
  image_path_ios: "assets/icons/ic_launcher_ios.png"
  android: true
  ios: true
  remove_alpha_ios: true
  # TODO: different icon for Android with rounded corners and another one, adaptive.
  # To update icons run : flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
    - assets/
    - assets/bible.db
    - assets/icons/ic_launcher_android_round.png
